BaSP-MR-47: async, await and fix issues POST, PUT and DELETE
BaSP-m2023/joaco-megarocket-server pull request #42
Opened 2023-05-20 17:59 UTC by ukiweskamp

2023-05-20 21:58 UTC, Federico-Peralta approved these changes
🚀

2023-05-20 23:04 UTC, iaracriscenti requested changes
Great job! Please check every response structure to match in every case.

2023-05-20 23:04 UTC, iaracriscenti commented on src/controllers/trainer.js
> +
Could you check if the email or dni entered already exists? Like u did on the post controller

2023-05-20 23:04 UTC, iaracriscenti commented on src/controllers/trainer.js
> +        error: true,
please add data: undefined

2023-05-20 23:04 UTC, iaracriscenti commented on src/controllers/trainer.js
> +    return res.status(400).json({
Same here, data value should be undefined and error should be a boolean

2023-05-21 20:39 UTC, JulianRiedinger7 commented on src/controllers/trainer.js
>        error,
this error should also be a boolean.. true in this case

2023-05-21 20:42 UTC, iaracriscenti commented on src/controllers/trainer.js
> +
Great addition! But this validation is still missing. I meant something like:
```
  const found = await Trainer.findOne({ $or: [{ dni }, { email }] });

    if (found) {
      return res.status(400).json({
        message: `The admin with DNI ${dni} or Email ${email} already exists`,
        data: undefined,
        error: true,
      });
    }
```

2023-05-21 21:07 UTC, iaracriscenti approved these changes

2023-05-21 21:11 UTC, merged