BaSP-MR-48: Super Admin TEST
BaSP-m2023/joaco-megarocket-server pull request #48
Opened 2023-05-23 03:27 UTC by ukiweskamp

2023-05-23 15:48 UTC, DelfiLT requested changes

2023-05-23 15:48 UTC, DelfiLT commented on src/tests/super-admin.test.js
> +describe('GET /api/Super-admin', () => {
Maybe you could test if the data is empty or not

2023-05-23 15:48 UTC, DelfiLT commented on src/tests/super-admin.test.js
> +    // eslint-disable-next-line no-underscore-dangle
try not to disable eslint

2023-05-23 15:48 UTC, DelfiLT commented on src/tests/super-admin.test.js
> +    expect(response.error).toBeTruthy();
Be careful with the response.error, should be response.body.error

2023-05-23 15:48 UTC, DelfiLT commented on src/tests/super-admin.test.js
> +    expect(response.error).toBeTruthy();
Check this in every case

2023-05-23 15:48 UTC, DelfiLT commented on src/tests/super-admin.test.js
> +  test('PUT if update success return 201', async () => {
Succes PUT should return 200

2023-05-23 21:01 UTC, ukiweskamp commented on src/tests/super-admin.test.js
> +  });
Good point, thanks!

2023-05-24 01:44 UTC, iaracriscenti approved these changes
Nicely done! ⭐ ⭐ ⭐

2023-05-24 01:59 UTC, DelfiLT approved these changes

2023-05-24 02:04 UTC, victoriassol approved these changes

2023-05-24 03:12 UTC, merged