BaSP-MR-34:  Members tests
BaSP-m2023/joaco-megarocket-server pull request #49
Opened 2023-05-23 04:10 UTC by Federico-Peralta

- Created members seed
- Tests with get, put, post and delete.
- Fixed Members controller

2023-05-23 13:15 UTC, Barbimillan commented on src/tests/members.test.js
> +  });
Maybe you could add a test with error server, e.g: route api incorrect

2023-05-23 13:52 UTC, victoriassol requested changes

2023-05-23 13:52 UTC, victoriassol commented on src/tests/members.test.js
> +// };
You should remove the comments!

2023-05-24 01:46 UTC, iaracriscenti approved these changes
Good job 🚀

2023-05-24 02:09 UTC, victoriassol approved these changes

2023-05-24 02:10 UTC, merged