BaSP-MR-42: Subscription test
BaSP-m2023/joaco-megarocket-server pull request #50
Opened 2023-05-23 17:54 UTC by MaateoC

2023-05-23 22:41 UTC, Federico-Peralta commented on src/tests/subscriptions.test.js
> +describe('GET /api/subscriptions', () => {
Since in this part you're testing the GET By ID the path should be '/api/subscriptions/:id'

2023-05-23 22:41 UTC, Federico-Peralta commented on src/tests/subscriptions.test.js
> +  });
Try to make a test with a server error. You can try to create a test where the api path is incorrect.

2023-05-24 00:17 UTC, Federico-Peralta commented on src/tests/subscriptions.test.js
> +describe('GET /api/subscriptions', () => {
I was referring to the part of describe. it should be describe('GET /api/subscriptions/:id')

2023-05-24 00:19 UTC, Federico-Peralta approved these changes
Approved

2023-05-24 01:31 UTC, iaracriscenti requested changes
Please check these comments, there are a few empty files that need to be checked.

2023-05-24 01:31 UTC, iaracriscenti commented on src/controllers/admins.js
Why is this file empty? 🤔

2023-05-24 01:31 UTC, iaracriscenti commented on src/models/Admins.js
Why does it look like you add a new file when it's already on master?

2023-05-24 01:31 UTC, iaracriscenti commented on src/models/Class.js
> +    default: 50,
Did you change it for some reason?

2023-05-24 01:31 UTC, iaracriscenti commented on src/routes/admins.js
Same here 🤔

2023-05-24 01:31 UTC, iaracriscenti commented on src/validations/admins.js
And here

2023-05-24 03:23 UTC, ukiweskamp approved these changes

2023-05-24 13:13 UTC, iaracriscenti approved these changes

2023-05-24 14:17 UTC, merged